### ISSUE TITLE
migrate tween wrappers from function-builder

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/twixt#1]
Migrate OpacityTo and MoveTo from function-builder to twixt.

3/17/16 dev meeting notes:

> CM: move tween animation wrappers (MoveTo, OpacityTo) from function-builder to twixt? OpacityTo is used in function-builder and could be used immediately in hookes-law. MoveTo is currently unused, but was exercised in earlier versions of function-builder.
SR: Since it can be reused, it should be factored out.  Also, there is a bug, the onUpdate option is never used.
JB: I could start making use of these now, and would try to replace the tweens that are currently used in Expression Exchange.
CM will move them over,will likely retrofit into Hooke’s Law too.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/hookes-law/issues/41 covers using these wrappers in hooks-law.

**Comment by pixelzoom** [comment]
Migration completed. Assign to @jbphet so he's aware of this and can start using them in Expression Exchange.

**Comment by jbphet** [comment]
I'm now aware of the twixt wrappers, but will likely not be using them in Expression Exchange due to a decision to not use TWEEN-based motion in the model, see https://github.com/phetsims/expression-exchange/issues/39.  Closing.
