### ISSUE TITLE
Delete SlidingScreen and replace usages with TransitionNode.

### ISSUE THREAD

**Issue by samreid** [phetsims/twixt#10]
From #8 and https://github.com/phetsims/area-model-common/issues/99

SlidingScreen was ported from Make a Ten (though still exists there as a copy), and is used by Equality Explorer.  TransitionNode is more general and flexible, and leverages Animation.js which is our proposed foundation for this kind of behavior.  We should delete SlidingScreen and replace usages with TransitionNode.

Assigning to @jonathanolson to work on this for Make a Ten. Depending on how that goes, he can recommend how to proceed for Fractions and Equality Explorer.  Tagging @pixelzoom so he is aware of this upcoming change.

**Comment by pixelzoom** [comment]
SlidingScreen is now used in fractions-common only.

**Comment by pixelzoom** [comment]
SlidingScreen is now used in fractions-common only, where there's an issue for it, https://github.com/phetsims/fractions-common/issues/3.   So closing this issue.
