### ISSUE TITLE
replace and delete MoveTo and OpacityTo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/twixt#18]
`MoveTo` and `OpacityTo` are 2 wrappers around TWEEN.  The idea was to insulate sims from the eventual replacement of TWEEN.   Since we now have animation support in TWIXT (Animation, Easing, etc.) that replaces TWEEN, the time has come to rewrite MoveTo and OpacityTo.

Current usages:

`MoveTo`
- [x] function-builder
- [x] unit-rates
- [x] SCENERY_PHET/Drawer - see phetsims/scenery-phet#396

`OpacityTo`
- [x] capacitor-lab-basics
- [x] function-builder

Since most of this is code that I'm responsible for, it would make sense for me to do this.  @ariel-phet OK for me to proceed?

**Comment by pixelzoom** [comment]
Hmmm... Looking inside `MoveTo` and `OpacityTo`, there's not really much there.  It might make more sense to replace uses of these with `Animation`, and then delete them.

**Comment by ariel-phet** [comment]
Sounds good, sorry for the delay

**Comment by pixelzoom** [comment]
Good, because I'm about half done with this :)

**Comment by pixelzoom** [comment]
All uses of MoveTo and Opacity have been replaced with Animation, and MoveTo and OpacityTo have been deleted.  All usages except one were in my sims.  

Assigning to @jonathanolson to review the replacement in capacitor-lab-basics, to decide whether he'd like to use a different variation of the Animation options, and whether to use `stepper: 'timer'`.  Feel free to close after that review.

**Comment by pixelzoom** [comment]
I just discovered the `object` and `attribute` options for animation targets, and I've used them in the above commits. For translation and opacity, this is much nicer than how I was using `setValue` and `getValue` options.

**Comment by pixelzoom** [comment]
Review of capacitor-lab-basics by @jonathanolson is moved to https://github.com/phetsims/capacitor-lab-basics/issues/252, so that this issue can be closed.

**Comment by pixelzoom** [comment]
There are a bunch of sims that are still preloading Tween via something like this in their package.json:

```js
    "preload": [
      "../sherpa/lib/Tween-r12.js"
    ],
```

I've create sim-specific issues for each such sim.
