### ISSUE TITLE
Animation fails with duration:0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/twixt#27]
If an Animation is created and run with `duration: 0`, it fails with `NaN` due to a divide-by-zero error.

This was the cause of https://github.com/phetsims/unit-rates/issues/215.  In Unit Rates, there's an animation that moves a marker along the number line, based on the number that's entered into a keypad.  

Here's the Animation definition in DoubleNumberLineAccordionBox:

```js
markerEditorAnimation = new Animation( {
  duration: 0.002 * Math.abs( destinationX - markerEditorNode.x ), // 2ms per 1 unit of distance
  easing: Easing.QUADRATIC_IN_OUT,
  object: markerEditorNode,
  attribute: 'x',
  to: destinationX
} );
```

If a value that is larger than the number line's range is entered into the keypad, then the marker moves to the far right end of the number line.   If you enter 2 such large values in a row, then the distance that the marker needs to move is zero, and the computed value of Animation option `duration` will also be zero.   

For example, here's the marker located at "333", and I'm about to enter "334".  This requires no movement of the marker, so `duration` is 0.

<img width="257" alt="screenshot_52" src="https://user-images.githubusercontent.com/3046552/72004335-65f67800-3208-11ea-92c1-b5d751d98401.png">

When you try to run an Animation with `duration: 0`, Animation `step` will have a divide-by-zero at line 312, where `this.length` is zero and `ratio` is therefore `NaN`.  

```js
312 const ratio = Utils.clamp( ( this.length - this.remainingAnimation ) / this.length, 0, 1 );
```

This causes failure further along in the code. In the case of Unit Rates, it failed down in `Easing.polynomialEaseInOutValue`, where an assertion noticed that the ratio was invalid.

In Unit Rates, I'm simply not going to create an Animation if `duration` is zero.  But this should be handled in Animation by either:

(a) an immediate assertion failure if `options.duration` is zero, or 
(b) the animation is a no-op and completes immediately when it's started.  

I don't know which option is better, but option (b) would have prevented having to add logic to Unit Rates.

**Comment by jonathanolson** [comment]
I'll lean towards (b) unless it seems unworkable in the code. Thanks for spotting!

**Comment by jonathanolson** [comment]
Implemented (b) above.

**Comment by pixelzoom** [comment]
I tested this by removing the workaround in phetsims/unit-rates#215.  Seems to work great.  Thanks, closing.
