### ISSUE TITLE
"dissolve" transition for games

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/twixt#6]
In phetsims/vegas#65 (comment), we identified scenarios where we want to use a "dissolved" transition to go from a challenge back to the level-selection screen.    This is used in games with a finite number of challenges per level and a "Start Over" button in the bar at the top of the screen.

Assigning to @jonathanolson to implement, since this is required for Area Model.

**Comment by jonathanolson** [comment]
Implemented with Transition/TransitionNode. Assigning @samreid for collaboration/review.

**Comment by samreid** [comment]
I created #11 for a more specific review issue.  @jonathanolson can/should we close this one?

**Comment by jonathanolson** [comment]
Review in https://github.com/phetsims/twixt/issues/11 sounds good. @pixelzoom, is "Use TransitionNode for main game animations" sufficient? Is there anywhere it should be documented?

**Comment by pixelzoom** [comment]
> @pixelzoom, is "Use TransitionNode for main game animations" sufficient? Is there anywhere it should be documented?

I'm not clear on what you're asking here.

**Comment by pixelzoom** [comment]
Yes, seems like this can be closed.
