### ISSUE TITLE
SlidingScreen should have a dispose function that unlinks

### ISSUE THREAD

**Issue by samreid** [phetsims/twixt#7]
SlidingScreen links to properties on creation, its dispose function should unlink.

Discovered in https://github.com/phetsims/area-model-common/issues/99

**Comment by jonathanolson** [comment]
So I hate to do this so quickly, but should be deprecate SlidingScreen in favor of TransitionNode (particularly once it is reviewed/etc.)?

**Comment by samreid** [comment]
We should proceed with #10, I'll unassign myself and put this issue on hold until then.

**Comment by pixelzoom** [comment]
This issue is no longer relevant, since SlidingScreen is deprecated and replaced by TransitionNode (which has a `dispose` function).  Closing.
